name: Build and Deploy Bookdown

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 📘 Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4'

      - name: 🔧 Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libfreetype6-dev \
            libfontconfig1-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libpng-dev \
            libtiff5-dev \
            libnetcdf-dev

      - name: 📦 Restore R package cache
        uses: actions/cache@v3
        with:
          path: renv/library
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: 📦 Restore R environment
        run: |
          Rscript -e 'install.packages("renv", repos = "https://cloud.r-project.org")'
          Rscript -e 'renv::restore()'
          Rscript -e 'if (!requireNamespace("bookdown", quietly = TRUE)) install.packages("bookdown")'

      - name: 📖 Render Bookdown site
        run: |
          Rscript -e 'bookdown::render_book("index.Rmd", output_dir = "docs")'

      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          cname: microbiome.complexdatainsights.com
