name: Test Bookdown Build

on:
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 📘 Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4'

      - name: 🔧 Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libfreetype6-dev \
            libfontconfig1-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libpng-dev \
            libtiff5-dev \
            libnetcdf-dev

      - name: 🔑 Set GitHub token for renv
        run: echo "GITHUB_PAT=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: 📦 Restore R package cache
        uses: actions/cache@v3
        with:
          path: renv/library/R-4.4/x86_64-pc-linux-gnu
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: 📦 Restore R environment
        run: |
          Rscript -e 'install.packages("renv", repos = "https://cloud.r-project.org")'
          Rscript -e 'renv::restore()'
          Rscript -e 'if (!requireNamespace("bookdown", quietly = TRUE)) install.packages("bookdown")'

      - name: 🛠 Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: 🧩 Use EDA GitBook layout
        run: |
          cp index-eda-gitbook.Rmd index.Rmd
          cp _bookdown-eda.yml _bookdown.yml

      - name: 📖 Render Bookdown site
        run: |
          Rscript -e 'bookdown::render_book("index.Rmd", output_dir = "docs")'
